### ISSUE TITLE
Question about the loss function

### ISSUE THREAD

**Issue by xuxy09** [AshishBora/csgm#1]
I don't understand why you use ||AG(z)-y|| as the loss function instead of using ||G(z)-x|| which makes more sense to me. I intuitively feel that multiplying A with x will lose lots of information. Looking forward to your explanation. Thanks!

**Comment by AshishBora** [comment]
Because we do not have access to `x`. We only have access to `A` and `y`, and we are trying to reconstruct `x`.

**Comment by xuxy09** [comment]
But y=Ax, if you do not have x, how can you get y?

**Comment by AshishBora** [comment]
`y = Ax` is computed outside the estimation procedure. The estimation procedure itself does not have access to `x`.

Think of it this way : Someone else has `x`. You give them an `A`, they compute `y = Ax`, and give `y` back to you. Can you find `x`? This is the problem compressed sensing is trying to solve.
