### ISSUE TITLE
Optimizer params need to get reinitialized

### ISSUE THREAD

**Issue by po0ya** [AshishBora/csgm#2]
In the `dcgan_estimator(hparams)` function of `celebA_estimators.py`, shouldn't the global_step variable and other variables of AdamOptimizer get reinitialized in each call of the nested `estimator(A_val, y_batch_val, hparams)` function?

**Comment by AshishBora** [comment]
Thanks for the catch. I have fixed it here: https://github.com/AshishBora/csgm/commit/aefa4219cd2032c54b59ed4f5449bc9ca698d604.

This should only further improve the results.
