### ISSUE TITLE
Dead link for datasets and models

### ISSUE THREAD

**Issue by qraleq** [AshishBora/csgm#4]
Could you please provide a working download link for datasets and models!

Thank you in advance!

Best regards!

**Comment by AshishBora** [comment]
Thanks for reporting this. The files have been restored and everything should work now. I will go ahead and close this issue, but please follow up if the problem persists.

**Comment by suhaslohit** [comment]
I think the links are dead again. It would be great if you could update them. Thanks

**Comment by Alex-adim** [comment]
Hi Suhas
does this link work for you  ?
https://www.dropbox.com/s/3o2vi1w1wde0ids/bora-pretrained.zip?dl=0

thanks
-Alex

**Comment by suhaslohit** [comment]
Yes, thank you.
