### ISSUE TITLE
question about the lose function in your paper and code

### ISSUE THREAD

**Issue by Renwoxin** [AshishBora/csgm#8]
hello,I want to consult with about your loss function for vae and GAN. In your paper , the loss function is ||AG(Z) - y||^2,but you used 'tf.matmul(x_hat_batch, A, name='y_hat_batch') ' to finish the funtion, but this code means ||G(Z)A - y|| ^ 2, there is no influence for the fuction,isn't it? I  really hope to hear from you soon. Thank you very much!

**Comment by AshishBora** [comment]
This is because in the paper, each column vector is an example, but in the code, each row is an example. The final loss is the same.

**Comment by Renwoxin** [comment]
@AshishBora thank you very much
